### ISSUE TITLE
Ets2 1.28

### ISSUE THREAD

**Issue by Leassus** [davidsantos-br/ETS2Sync-Helper-4#17]
ETS 1.28 when loading a synced save it has detected game change and so it will not work any way to fix this?

**Comment by Nuno18** [comment]
Hi Leassus.
Unfortunately the only way to fix it is wait for David Santos do the upgrade for version 1.28 of the ETS2Sync-Helper.

King Regards,
Nuno

**Comment by DaviMedrade** [comment]
Hmm. I haven't been playing lately, so I didn't know the save was changed with this update. Should be working in a few hours.

**Comment by j1m1l0k0** [comment]
Agora tem carga dupla @davidsantos-br

**Comment by j1m1l0k0** [comment]
@davidsantos-br  alias porque não cria seu próprio Mod online ? no estilo Lobby

**Comment by DaviMedrade** [comment]
I was trying make it work with changes on the server only, but the changes to the save properties apparently require a new version of ETS2Sync after all. Unfortunately, this will take a bit longer to fix. Another day or two. I formatted my computer last week and I need to reinstall and reconfigure my development environment (which can take several hours).

**Comment by Leassus** [comment]
Its nice you can do this so quick though.
Since you diddent play for a while ,  maybe u lost intrest.
but seems like you are updating it so respect :)

**Comment by GatoMalo507** [comment]
@davidsantos-br Thanks for your work, we hope you can finish the update of the ETS2sync helper - v.1.28

**Comment by DaviMedrade** [comment]
It's the variants again. I was able to sync using a test version of ETS2Sync Helper, but only with all the DLCs enabled and with variant sanitization disabled on the server.

In the save, each job trailer is described as a cargo (say, `used_packag` for a cargo of used packages), but for each cargo there is a choice of trailers that can be used, so the variant is a number that specifies which trailer is being used for that job. So a cargo of `used_packag` with variant 0 will be used packages in one kind of trailer, while the same cargo with variant 1 will be used packages in another kind of trailer.

The server sanitizes the variant because some DLCs add trailers, and those can be used for cargo outside of the area of the DLC, depending on the cargo and trailer. For example, if the person has the Scandinavia DLC, trailers added by it could theoretically be used even for jobs outside of Scandinavia. Say, if Scandinavia adds variant 3 for `used_packag`, even a job from Berlin to Paris could use that variant. So filtering it just by location doesn't work (and the Schwarzmüller DLC adds several trailer variants even though it doesn't correspond to a specific area on the map).

So if a job specifies a trailer variant the user doesn't have (because they don't own that DLC) when they sync and load the save the game will see jobs with variants it doesn't have. That triggers an Economy Reset (the “Game Change Detected” message) which undoes the sync.

Apparently in 1.28 they changed the way those variants are tracked, so when the server tries to sanitize them to make the jobs work for all players the game detects that somehow and triggers an Economy Reset anyway.

I'm looking into it because variant sanitization is very much necessary. Without it, I'd have to extract job lists for each possible combination of DLCs (if my math is right, that would be 256 lists for ETS2 and 16 for ATS), and that's just not feasible.

![20170823231652_1](https://user-images.githubusercontent.com/39162/29646335-3de3da2a-8859-11e7-8354-4253a27fe05c.jpg)

**Comment by maxinnee** [comment]
working or not?

**Comment by DaviMedrade** [comment]
Not yet. I'm confident that I figured out what the problem is, so now I'm working on a fix.

**Comment by maxinnee** [comment]
ok, ty

**Comment by DaviMedrade** [comment]
Didn't manage to finish it today. Unless some unforeseen complication arises, I expect to release the new version within 24 hours.

**Comment by DiegoSi** [comment]
Hello David, the problem still persisted?

**Comment by DaviMedrade** [comment]
Yes. The game keeps resetting the economy when I try to sync without the Schwarzmüller DLC, no matter what I do. I'm trying to figure out why.

**Comment by DaviMedrade** [comment]
I'm at a loss. There are cargoes for which variant 0 is the Schwarzmüller version (the base game versions being variants 1 and 2), and when a such job has variant 0 and the DLC is not installed, the game still somehow knows that variant is for Schwarzmüller, so it resets the economy since Schwarzmüller isn't there.

I still don't know how it knows about a DLC that isn't installed, let alone how to find the correct variant in that case. There are dozens of cargoes in that situation so figuring out the valid variants for each cargo for each DLC one by one by hand isn't an option. Requiring people to buy the DLC isn't really an option either.

I guess it'll take a few more days to tackle this issue. The upside is that I'm gaining a deeper understanding of the game files and I implemented a job filter that is a lot more robust, so, once I figure this out, updates for new DLCs should be a lot easier to make (and shouldn't even require releasing a new version of the app).

**Comment by DiegoSi** [comment]
Ok David, I understand and I agree with you, I am looking forward to the application sync helper, without it the game gets very bland to play multplayer.






________________________________
De: David Santos <notifications@github.com>
Enviado: sexta-feira, 25 de agosto de 2017 06:17
Para: davidsantos-br/ETS2Sync-Helper-4
Cc: DiegoSi; Manual
Assunto: Re: [davidsantos-br/ETS2Sync-Helper-4] Ets2 1.28 (#17)


I'm at a loss. There are cargoes for which variant 0 is the Schwarzmüller version (the base game versions being variants 1 and 2), and when a such job has variant 0 and the DLC is not installed, the game still somehow knows that variant is for Schwarzmüller, so it resets the economy since Schwarzmüller isn't there.

I still don't know how it knows about a DLC that isn't installed, let alone how to find the correct variant in that case. There are dozens of cargoes in that situation so figuring out the valid variants for each cargo for each DLC one by one by hand isn't an option. Requiring people to buy the DLC isn't really an option either.

I guess it'll take a few more days to tackle this issue. The upside is that I'm gaining a deeper understanding of the game files and I implemented a job filter that is a lot more robust, so, once I figure this out, updates for new DLCs should be a lot easier to make (and shouldn't even require releasing a new version of the app).

**Comment by Simeta** [comment]
Hello David,

If it is working for people that own the Schwarzmüller DLC could you maybe release that update with a warning about it still not working if you don't own it? Then update it once you work it out?

I'd also assume the ATS side of the program is working fine?

**Comment by DaviMedrade** [comment]
I'd rather release a version that doesn't work with Schwarzmüller than one that requires it. I mean, if it requires the DLC those who don't have it would have to spend money to get it, while a version that doesn't work with it would require people who own it to disable it, which they can do for free.

Still, I'll work on it a little more before I decide on that. I'd rather not impose those kinds of conditions, even temporarily, unless there's no other way. I'm still not happy with the fact that I had to drop support of binary saves when they released 1.25…

**Comment by DaviMedrade** [comment]
I was finally able to test it with another profile that I made after uninstalling all DLCs. The sync succeeded with variant 0 (which is supposedly from the base game). Then I reinstalled all DLCs except Schwarzmüller and tried to sync another profile that I made without Schwarzmüller, and the sync failed. So the issue may not be Schwarzmüller's fault after all. It might be another DLC altogether or it might be a weird interaction between another DLC and Schwarzmüller (or lack thereof).

Still working on it.

**Comment by DaviMedrade** [comment]
Hm. Scandinavia and High Power Cargo Pack both have references to Schwarzmüller. When I disabled both along with it (leaving Vive La France, Heavy Cargo Pack, and Going East) the sync worked.

**Comment by DaviMedrade** [comment]
OK, the variant sanitizer is working. Apparently the game puts the list of variants in reverse of what I expected.

The main culprit was Scandinavia with its double trailers—which makes sense: it was the main change of this version of ETS2, so it's not weird that it's the main cause of the break.

The variant sanitizer dodges Schwarzmüller by detecting when it is the variant of the job and selecting another. Before the doubles any available variant was OK, but after the update the variant selected by the sanitizer for some jobs would end up being a double trailer in a job that couldn't use one (i.e. a job that starts or ends outside of Scandinavia).

Unless ATS presents unexpected complications, the new version should be out soon.

**Comment by Leassus** [comment]
Cool you did this quite quickly im cant wait for the release keep up the good work :)

**Comment by maxinnee** [comment]
me too <3

**Comment by DiegoSi** [comment]
Very good, that is managing to solve the problem with the sync of ets2, good work David.

**Comment by DaviMedrade** [comment]
The update has been released.

**Comment by Bru13** [comment]
Where can we download already updated?

**Comment by DaviMedrade** [comment]
https://github.com/davidsantos-br/ETS2Sync-Helper-4/releases

**Comment by Bru13** [comment]
thank you!


2017-08-26 13:36 GMT-03:00 David Santos <notifications@github.com>:
