### ISSUE TITLE
“Game Change Detected” after syncing

### ISSUE THREAD

**Issue by xeiki** [davidsantos-br/ETS2Sync-Helper-4#5]
Hello,
Is your webserver down or something like that?
Because my Guys and me we are getting this message
"**HTTP 503 Service Temporarily Unavailable**"
here is an screenshot:
https://s23.postimg.org/9fnhkog4r/fnkjsdfnkjsdf.png
When comes your webserver back online?

**Comment by DaviMedrade** [comment]
Hi.

My server is not down. The server where the job list comes from (ets2sync.com) is. In order to make it work again I'll have to get job lists from somewhere else, or find out how to generate my own.

My computer isn't working well, though, so it might take me a couple of weeks before I can work on this.

**Comment by xeiki** [comment]
I found something: https://goo.gl/QDHpnj 
The owner of ets2sync has ordered a new server and he is waiting for delivery.
So we just need to wait :) .

**Comment by DaviMedrade** [comment]
Thanks for the update, @eikichi87.

I've put a new job list, but it's static. I need to create a few more and figure out a way to make the server alternate between them (say, one per week like ets2sync.com does). But if ets2sync.com is coming back, I might not need to bother with that except for ATS.

Regarding ATS and the France DLC, see #6.

**Comment by xeiki** [comment]
I think it does not work very well.
Because when a friend and I Sync the jobslist with your program happens this:

When we two are in Kralskrona(Sweden) and save the game and Sync the joblist with your program and load the save game back, it drops us to our home garages, like I'm in Frankfurt(Germany) and my friend is in Stuttgart(Germany). And the Jobs  are not Synced at all.

And if we load the save game back we get this message here:
https://s30.postimg.org/4ur40u7tt/34tqt43tq34t.png

So can you fix this?

**Comment by xeiki** [comment]
and the guy from ets2sync has written something again here
https://goo.gl/eVZd7W

Why you dont contact him and ask him for the api or how hes doing this joblist thing? ^^

**Comment by DaviMedrade** [comment]
I'll look into it.

Do you have the France DLC?

The job list I am using now is coming from an actual game save, so the only ways it could not work is if I extracted it wrong, or if I failed to filter out some cities from the France DLC. So, if you don't have it, that might explain why it works for me and not for you. I mean, if you load a save with cities you don't have, the game might consider it a “game change”.

I'll check the list again.

**Comment by xeiki** [comment]
No I dont have France DLC :) .
Just the Main game and Going East, Scandinavia.

> I'll check the list again.

Ok, Thanks.

**Comment by DaviMedrade** [comment]
@eikichi87, I've updated the filters. The list I had was generated from the names of the files. I used a tool provided by SCS to unpack the .scs files from the base game and the DLCs. In each there is a folder named “cities” with a .sii file for each city. So I just listed all files and removed the .sii (so def\city\venice.sii would go into the list as “venice”). What I didn't notice is that the name of the city in the save didn't always match the name of the file. For example, the file “venice.sii” actually defined a city named “venezia”.

Compounding the problem, I only had lists for the DLCs, and any city not in those lists was assumed to be a part of the base game. So if there is a file in a DLC defining a city with a different name, it was assumed that it was a city from the base game and so it wasn't filtered out when that DLC was not selected in the program.

Now I recreated the list, parsing the files to get the actual name instead of using the name of the file, and included a list of cities in the base game. That way, it shouldn't be possible for this problem to happen again.

Please, let me know if it works now.

**Comment by xeiki** [comment]
Sorry it does not work, we get the same Error message like this:
https://s28.postimg.org/5moyclgq5/20161229182530_1.jpg

Other question, so If we buy the France DLC it does then work with your program again?
Is it because of not having the France DLC not working? I am right?

**Comment by DaviMedrade** [comment]
I think that the issue is the France DLC, but I can't be sure, so I can't tell you to spend money on it when it might not solve the problem.

If you could add me on Steam, it would be easier for us to troubleshoot this.

http://steamcommunity.com/id/davidsantos_br

**Comment by DaviMedrade** [comment]
Another thing I'd like to know is if the same message appears if you do the process normally but click “Clear Jobs” instead of “Sync Jobs”. That will let me know if the problem is with the job list or with the process of inserting the jobs into the save.

**Comment by DaviMedrade** [comment]
It seems that the issue is not the France DLC. I just disabled it and synced a save I made before I bought it, and it worked without issues.

![20161229175903_1](https://cloud.githubusercontent.com/assets/39162/21553669/b7e3228c-cdf0-11e6-8482-7a49ba5b0d8b.jpg)

**Comment by DaviMedrade** [comment]
I've just released Version 4.1.0. It adds support for Vive la France, but it probably won't fix the problem you're having. Still, please try it out, because it saves an unencrypted copy of the original save before syncing. That way I can compare the save before and after syncing to see what went wrong.

If after syncing you see that message, do not try to sync again. Then, go to “Documents\Euro Truck Simulator 2”, type Ctrl+F, then in the search box type “*.sii.raw.txt”. It should find one file named “game.sii.raw.txt” (if you only tried syncing one save after updating the app). Right-click on the file and select “Open file location”. It should open a folder. In it, among other files, there should be a “game.sii” and a “game.sii.raw.txt”. I would need you to send me both. Just compress them both and send the .zip/.rar/.7z file to david@dsantosdev.com.

Thanks for your help with this.

**Comment by xeiki** [comment]
Hey man,
I have a video just because of this error so that you can understand the thing better and I have sent you the files to you that you want, hope you got it was almost 10MB big, you will also immediately on Steam add.

Video: https://youtu.be/fdZ4byWsrzg

Thank you again for your concern :)

**Comment by whiskeyalpha90** [comment]
Hi guys,

Was this resolved? I am getting the same game change detected error, but only when trying to sync jobs. When clearing it loads fine.

**Comment by DaviMedrade** [comment]
Can you try creating a new profile in the game and see if the issue still happens?

**Comment by DaviMedrade** [comment]
Also, can you try checking the integrity of the local game files?

Right-click on the game on Steam → Properties → ”Local Files” tab → Verify Integrity of Local Cache.

**Comment by whiskeyalpha90** [comment]
Hi David,

I verified local cache and also started a new profile and same issue I'm afraid. Game change detected.

I noticed this in the log when trying to load after syncing: "Economy reset - at least one referenced object is missing"

I have all of the DLC apart from a few paint addons and I ticked all 4 options in the application.

Thanks.

**Comment by DaviMedrade** [comment]
That is indeed helpful. Narrows it down a lot. I was thinking it might have something to do with the time inserted, but now I know it isn't that.

Just to be sure, do you have the Schwarzmüller DLC?

**Comment by whiskeyalpha90** [comment]
Glad I could help :)

I do not have that DLC. You think that might be it?

**Comment by DaviMedrade** [comment]
It's the only one that I can think of besides France, Scandinavia and High Power Cargo Pack that has anything to do with cargo—Going East doesn't add new cargo options—, which is the only thing the program changes in the save.

I thought I could still be missing a city (i.e. adding jobs to a city in a DLC you don't have) but that doesn't make sense because you have all of them.

I'll boot into Windows soon and then I'll make some tests.

**Comment by DaviMedrade** [comment]
Do you have ATS? Can you test if the same thing happens there? I don't think it would, but just to be sure.

**Comment by whiskeyalpha90** [comment]
Hey, I don't have enough hours clocked on ATS to try on TruckersMP, but I was able to test on ATS singleplayer. Works fine, synced and no error message :)

**Comment by DaviMedrade** [comment]
I have finally been able to reproduce the problem. The sync was working normally, but it started giving out this “Game Change Detected” message when I uninstalled the Schwarzmüller DLC.

Now I just need to figure out why this happens.

**Comment by DaviMedrade** [comment]
@havok962, @eikichi87, please test again.

Each job has a cargo (what is to be carried) and a variant (which of the possible trailers for that cargo is to be used).

For example, the cargo “apples” can be carried on a “krone.profiliner” or on a “schmitz.universal” trailer. The variant is a sequential number specifying which trailer from the ones available for that cargo is selected for that job. So, for a cargo of apples, a variant of 0 (zero) would mean the krone.profiliner and a variant of 1 (one) would specify the schmitz.universal.

Schwarzmüller adds options for the existing cargoes. People who have that DLC can also have a cargo of apples with a variant of 2, which is a “schw_curtain” trailer. So, when I extracted the job list from one of my saves, it had, for example, cargo of apples with variant 2. Those who don't have the DLC can only have variant 0 or 1, so when the game tries to load the save it sees a variant of 2 and doesn't find that trailer, which means that, from the game's point of view, “at least one referenced object is missing”, triggering an Economy Reset.

Earlier versions of the game didn't behave this way. If you tried to load a save with invalid variants before, the save would load normally. The job would appear with the last trailer available (so a cargo of apples with variant 2 would use the variant 1 trailer), but the weight of the cargo in the Job Market would appear as zero.

Apparently that behavior was changed in ETS2 version 1.26, where it triggers an Economy Reset instead.

By inspecting the game files, I was able to generate a list with the maximum variant that is allowed for each cargo without the Schwarzmüller DLC. Now, when the server is going to send the job list to ETS2Sync Helper, it checks the variants and fixes them whenever necessary.

**Comment by Koffeeuk** [comment]
Hi,  just like to say first thank you for the mod, truly thank you. 
i can say that i get the error myself  and i have the french DLC and other major ones that do cargo, but i don't however have the Schwarzmüller DLC.   Are you suggesting a new profile for version 1.26 to correct the Game change detected error?

**Comment by xeiki** [comment]
Okay man thanks, it worked :) 
Happy New Year to you all guys :D

**Comment by DaviMedrade** [comment]
@Koffeeuk, no, a new profile wouldn't help. I've made a change on the server to fix incorrect variant numbers which should have fixed it. Please try again and let me know if the message still appears.

**Comment by Koffeeuk** [comment]
fixed thanks again and happy new year to you!

**Comment by whiskeyalpha90** [comment]
Hi David,

Many thanks for your responses and solution over the new year. I have tested and works great!

Happy New Year to you!

**Comment by whiskeyalpha90** [comment]
How often do the jobs update?

**Comment by DaviMedrade** [comment]
Right now they don't. I extracted static job lists from saves, one for each game, just to get the sync working after ets2sync.com went offline.

ets2sync.com updated it every week. I can't just generate job lists automatically because I don't have a database with the distances between cities, prices and times of ferries, and the kinds of cargo that can be transported to and from each company, so extracting the jobs from an actual save is the best way to get lists as realistic as possible.

What I'm thinking of doing is extracting a number of lists, say 4 to 8 lists for each game, and cycle through them one per week.

**Comment by MrBuggatore** [comment]
Hi, unfortunately me and my VTC friends still get the Game Change Detected error, any solution?

**Comment by whiskeyalpha90** [comment]
A cycle would be good, just so there would be a difference in jobs every week

@MrBuggatore not to hijack David's github, but make sure you have economy reset turned off in your config.cfg and preview_config.cfg files. I noticed this last week when trying to get mine working.

**Comment by MrBuggatore** [comment]
@havok962 force economy reset was already set to 0 in my files.

**Comment by DaviMedrade** [comment]
@MrBuggatore, I need you to check if the same message appears if you use “Clear Jobs” instead of “Sync Jobs”, if the same happens in ATS if you have it, and I need to know which of these DLCs you have: Going East!, Scandinavia, High Power Cargo Pack, Vive la France!, and Schwarzmüller.

**Comment by MrBuggatore** [comment]
Hi David, I don't get the same error using Clear Jobs, and jobs are correctly cleared. I don't have ATS, and my DLCs are Going East and High Power Cargo and some paintjobs.

**Comment by DaviMedrade** [comment]
@MrBuggatore, I made a little change on the server. Please test again.

**Comment by MrBuggatore** [comment]
@davidsantos-br Same error, maybe you need this: [game.sii.raw.txt](https://github.com/davidsantos-br/ETS2Sync-Helper-4/files/690660/game.sii.raw.txt)

**Comment by DaviMedrade** [comment]
I was able to figure out the problem. It was a lingering variant issue that happened when you didn't have Scandinavia.

The server went down just as I was about to upload a fix. The datacenter is looking into the server issue. As soon as it comes back up I'll upload the fix.

**Comment by DaviMedrade** [comment]
Server is up. Issue is fixed.
